base: /
dependencies:
  - tim/my-project
languages:
  -
    title: English
    enabled: true
    locale: en_US.utf8
    hreflang: ''
    base: /
    websiteTitle: ''
    navigationTitle: English
    flag: global
    languageId: 0
rootPageId: 1
websiteTitle: ''
