name: Testing and TER deployment

on: [push, pull_request]

jobs:
  tests:
    name: Run tests using PHP ${{ matrix.php-versions }} with TYPO3 ${{ matrix.typo3-versions }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ["8.2"]
        typo3-versions: ["13.1"]

    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: intl, mbstring, xml, soap, zip, curl

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: php-${{ matrix.php-versions }}-typo3-${{ matrix.typo3-versions }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: |
            php-${{ matrix.php-versions }}-typo3-${{ matrix.typo3-versions }}-composer-
            php-${{ matrix.php-versions }}-typo3-

      - name: Install composer dependencies
        run: composer require typo3/minimal "^${{ matrix.typo3-versions }}" --prefer-dist --no-progress --no-suggest

      #- name: Run tests
      # run: composer run-script test

  deploy-hostinger:
    name: Deploy to Hostinger (SSH)
    needs: tests
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOSTINGER_SSH_HOST }}
          username: ${{ secrets.HOSTINGER_SSH_USER }}
          key: ${{ secrets.HOSTINGER_SSH_KEY }}
          password: ${{ secrets.HOSTINGER_SSH_PASSWORD }}
          port: 65002

          script: |
            cd ${{ secrets.HOSTINGER_PATH }}
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php vendor/bin/typo3 cache:flush
